; Project Euler - Problem 29
; How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?

(defn exp [n m]
  (reduce *' (repeat m n))
)

(def euler29
  (count
    (set 
      (for [a (range 2 101)
            b (range 2 101)]
        (exp a b)
      )
    )
  )
)

(println euler29)